#!/bin/bash
set -euo pipefail

# =============================================================================
# devcontainer-wt installer
#
# Installs the devcontainer-wt template into the current project.
# Downloads template files from GitHub and sets up the .devcontainer/ directory.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/kenfdev/devcontainer-wt/main/install.sh | bash
#
# Minimum mode (no Traefik, no shared infra, no custom network):
#   curl -fsSL https://raw.githubusercontent.com/kenfdev/devcontainer-wt/main/install.sh | bash -s -- --minimum
#
# Or download and run:
#   curl -fsSL -o install.sh https://raw.githubusercontent.com/kenfdev/devcontainer-wt/main/install.sh
#   chmod +x install.sh
#   ./install.sh [--minimum]
# =============================================================================

REPO="kenfdev/devcontainer-wt"
BRANCH="main"
MODE="full"

# --- Parse arguments ---

for arg in "$@"; do
  case "$arg" in
    --minimum) MODE="minimum" ;;
    -h|--help)
      echo "Usage: install.sh [--minimum]"
      echo "  --minimum  Install simplified template (no Traefik, no shared infra)"
      exit 0
      ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

# --- Colors ---

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${BLUE}[devcontainer-wt]${NC} $*"; }
warn()    { echo -e "${YELLOW}[devcontainer-wt]${NC} $*"; }
error()   { echo -e "${RED}[devcontainer-wt]${NC} $*" >&2; }
success() { echo -e "${GREEN}[devcontainer-wt]${NC} $*"; }

# Prompt helper that reads from /dev/tty (works with curl | bash).
ask() {
  local prompt="$1"
  local default="$2"
  local answer
  echo -en "${BLUE}[devcontainer-wt]${NC} ${prompt} " > /dev/tty
  read -r answer < /dev/tty
  echo "${answer:-$default}"
}

# --- Prerequisites ---

for cmd in curl git tar; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    error "${cmd} is required but not installed."
    exit 1
  fi
done

if ! git rev-parse --git-dir > /dev/null 2>&1; then
  error "Not a git repository. Run this from inside your project."
  exit 1
fi

echo
info "${BOLD}Installing devcontainer-wt template${NC} (mode: ${MODE})"
info "Source: github.com/${REPO}@${BRANCH}"
echo

# --- Handle existing .devcontainer/ ---

if [ -d ".devcontainer" ]; then
  warn "Existing .devcontainer/ directory detected."
  answer=$(ask "Overwrite (o) or backup and replace (b)? [b]:" "b")
  case "$answer" in
    o|O)
      info "Removing existing .devcontainer/..."
      rm -rf .devcontainer
      ;;
    *)
      backup_dir=".devcontainer.backup.$(date +%Y%m%d%H%M%S)"
      info "Backing up to ${backup_dir}/..."
      mv .devcontainer "$backup_dir"
      success "Backup created: ${backup_dir}/"
      ;;
  esac
  echo
fi

# --- Download template ---

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

info "Downloading template from GitHub..."
if ! curl -fsSL "https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz" | tar xz -C "$TMPDIR"; then
  error "Failed to download template. Check your network connection."
  exit 1
fi
TEMPLATE_DIR="${TMPDIR}/devcontainer-wt-${BRANCH}/template"

if [ ! -d "$TEMPLATE_DIR" ]; then
  error "Unexpected archive structure. Expected directory: devcontainer-wt-${BRANCH}/template"
  exit 1
fi

# --- Install core files ---

info "Installing .devcontainer/..."
mkdir -p .devcontainer/hooks

cp "$TEMPLATE_DIR/.devcontainer/devcontainer.json.template" .devcontainer/
cp .devcontainer/devcontainer.json.template .devcontainer/devcontainer.json
cp "$TEMPLATE_DIR/.devcontainer/Dockerfile"                 .devcontainer/
cp "$TEMPLATE_DIR/.devcontainer/hooks/post-start.sh"        .devcontainer/hooks/
cp "$TEMPLATE_DIR/.devcontainer/docker-compose.local.yml.template" .devcontainer/

if [ "$MODE" = "minimum" ]; then
  cp "$TEMPLATE_DIR/.devcontainer/minimum/init.sh"            .devcontainer/
  cp "$TEMPLATE_DIR/.devcontainer/minimum/docker-compose.yml" .devcontainer/
else
  cp "$TEMPLATE_DIR/.devcontainer/init.sh"            .devcontainer/
  cp "$TEMPLATE_DIR/.devcontainer/docker-compose.yml" .devcontainer/
fi

chmod +x .devcontainer/init.sh
chmod +x .devcontainer/hooks/post-start.sh

info "Installing .env.app.template..."
cp "$TEMPLATE_DIR/.env.app.template" .

info "Installing .worktreeinclude..."
cp "$TEMPLATE_DIR/.worktreeinclude" .

# Install worktree hooks
info "Installing .worktree/hooks/..."
mkdir -p .worktree/hooks
cp "$TEMPLATE_DIR/.worktree/hooks/on-create.sh" .worktree/hooks/
cp "$TEMPLATE_DIR/.worktree/hooks/on-delete.sh" .worktree/hooks/
chmod +x .worktree/hooks/on-create.sh
chmod +x .worktree/hooks/on-delete.sh

# Install root docker-compose.yml for full mode
if [ "$MODE" = "full" ]; then
  info "Installing docker-compose.yml (shared infrastructure)..."
  cp "$TEMPLATE_DIR/docker-compose.yml" .
fi

# Create .devcontainer/.gitignore for generated files
cat > .devcontainer/.gitignore <<'GITIGNORE'
# Generated by devcontainer-wt (per-worktree, not tracked)
.env
.env.app

# Per-developer devcontainer (copied from template)
devcontainer.json

# Local overrides (personal, not tracked)
*.local.*
GITIGNORE

# Add .worktreeinclude.local to root .gitignore if not already present
if [ -f ".gitignore" ]; then
  if ! grep -q '.worktreeinclude.local' .gitignore; then
    printf '\n# Personal worktreeinclude (not tracked)\n.worktreeinclude.local\n' >> .gitignore
  fi
else
  cat > .gitignore <<'ROOTGITIGNORE'
# Personal worktreeinclude (not tracked)
.worktreeinclude.local
ROOTGITIGNORE
fi

success "Core template files installed."

# --- AI skill files (optional, recommended) ---

echo
info "The devcontainer-wt AI skill helps AI agents (Claude, Copilot, etc.)"
info "understand your devcontainer-wt setup and assist with customization."
answer=$(ask "Install AI skill files? (recommended) [Y/n]:" "Y")
case "$answer" in
  n|N)
    info "Skipping AI skill files."
    ;;
  *)
    mkdir -p .agents/skills/devcontainer-wt/references
    cp "$TEMPLATE_DIR/.agents/skills/devcontainer-wt/SKILL.md" \
       .agents/skills/devcontainer-wt/
    cp "$TEMPLATE_DIR/.agents/skills/devcontainer-wt/references/CUSTOMIZING.md" \
       .agents/skills/devcontainer-wt/references/
    success "AI skill files installed."
    ;;
esac

# --- Done ---

echo
success "devcontainer-wt installed successfully! (mode: ${MODE})"
echo
info "${BOLD}Next steps:${NC}"
info "  1. Edit .devcontainer/devcontainer.json  -- add language features & extensions"
info "  2. Edit .devcontainer/Dockerfile          -- add system dependencies"
if [ "$MODE" = "full" ]; then
  info "  3. docker compose up -d                   -- start shared infrastructure"
  info "  4. Edit docker-compose.yml                -- add infra (Postgres, Redis, etc.)"
  info "  5. Edit .env.app.template                 -- add per-worktree env vars"
  info "  6. Edit .devcontainer/hooks/post-start.sh -- add project setup (deps, DB, migrations)"
  info "  7. Open in VS Code and 'Reopen in Container'"
else
  info "  3. Edit .devcontainer/hooks/post-start.sh -- add project setup (deps, build steps)"
  info "  4. Open in VS Code and 'Reopen in Container'"
  echo
  info "To upgrade to full mode (Traefik, shared infra, custom network):"
  info "  Re-run the installer without --minimum"
fi
echo
info "If you are using git-wt, configure worktree hooks (recommended):"
info "  git config wt.basedir .git/wt"
info "  git config --add wt.hook \".worktree/hooks/on-create.sh\""
info "  git config --add wt.deletehook \".worktree/hooks/on-delete.sh\""
echo
info "Customization guide:"
info "  https://github.com/${REPO}/blob/${BRANCH}/template/.agents/skills/devcontainer-wt/references/CUSTOMIZING.md"
echo
