#!/bin/bash
set -euo pipefail

# =============================================================================
# devcontainer-wt installer
#
# Installs the devcontainer-wt template into the current project.
# Downloads template files from GitHub and sets up the .devcontainer/ directory.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/kenfdev/devcontainer-wt/main/install.sh | bash
#
# Or download and run:
#   curl -fsSL -o install.sh https://raw.githubusercontent.com/kenfdev/devcontainer-wt/main/install.sh
#   chmod +x install.sh
#   ./install.sh
# =============================================================================

REPO="kenfdev/devcontainer-wt"
BRANCH="main"

# --- Colors ---

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${BLUE}[devcontainer-wt]${NC} $*"; }
warn()    { echo -e "${YELLOW}[devcontainer-wt]${NC} $*"; }
error()   { echo -e "${RED}[devcontainer-wt]${NC} $*" >&2; }
success() { echo -e "${GREEN}[devcontainer-wt]${NC} $*"; }

# Prompt helper that reads from /dev/tty (works with curl | bash).
ask() {
  local prompt="$1"
  local default="$2"
  local answer
  echo -en "${BLUE}[devcontainer-wt]${NC} ${prompt} " > /dev/tty
  read -r answer < /dev/tty
  echo "${answer:-$default}"
}

# --- Prerequisites ---

for cmd in curl git tar; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    error "${cmd} is required but not installed."
    exit 1
  fi
done

if ! git rev-parse --git-dir > /dev/null 2>&1; then
  error "Not a git repository. Run this from inside your project."
  exit 1
fi

echo
info "${BOLD}Installing devcontainer-wt template${NC}"
info "Source: github.com/${REPO}@${BRANCH}"
echo

# --- Handle existing .devcontainer/ ---

if [ -d ".devcontainer" ]; then
  warn "Existing .devcontainer/ directory detected."
  answer=$(ask "Overwrite (o) or backup and replace (b)? [b]:" "b")
  case "$answer" in
    o|O)
      info "Removing existing .devcontainer/..."
      rm -rf .devcontainer
      ;;
    *)
      backup_dir=".devcontainer.backup.$(date +%Y%m%d%H%M%S)"
      info "Backing up to ${backup_dir}/..."
      mv .devcontainer "$backup_dir"
      success "Backup created: ${backup_dir}/"
      ;;
  esac
  echo
fi

# --- Download template ---

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

info "Downloading template from GitHub..."
if ! curl -fsSL "https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz" | tar xz -C "$TMPDIR"; then
  error "Failed to download template. Check your network connection."
  exit 1
fi
TEMPLATE_DIR="${TMPDIR}/devcontainer-wt-${BRANCH}"

if [ ! -d "$TEMPLATE_DIR" ]; then
  error "Unexpected archive structure. Expected directory: devcontainer-wt-${BRANCH}"
  exit 1
fi

# --- Install core files ---

info "Installing .devcontainer/..."
mkdir -p .devcontainer/hooks

cp "$TEMPLATE_DIR/.devcontainer/devcontainer.json"        .devcontainer/
cp "$TEMPLATE_DIR/.devcontainer/init.sh"                  .devcontainer/
cp "$TEMPLATE_DIR/.devcontainer/docker-compose.yml"       .devcontainer/
cp "$TEMPLATE_DIR/.devcontainer/docker-compose.infra.yml" .devcontainer/
cp "$TEMPLATE_DIR/.devcontainer/Dockerfile"               .devcontainer/
cp "$TEMPLATE_DIR/.devcontainer/hooks/post-start.sh"      .devcontainer/hooks/

chmod +x .devcontainer/init.sh
chmod +x .devcontainer/hooks/post-start.sh

info "Installing .env.app.template..."
cp "$TEMPLATE_DIR/.env.app.template" .

# Create .devcontainer/.gitignore for generated files
cat > .devcontainer/.gitignore <<'GITIGNORE'
# Generated by devcontainer-wt (per-worktree, not tracked)
.env
.env.app
GITIGNORE

success "Core template files installed."

# --- AI skill files (optional, recommended) ---

echo
info "The devcontainer-wt AI skill helps AI agents (Claude, Copilot, etc.)"
info "understand your devcontainer-wt setup and assist with customization."
answer=$(ask "Install AI skill files? (recommended) [Y/n]:" "Y")
case "$answer" in
  n|N)
    info "Skipping AI skill files."
    ;;
  *)
    mkdir -p .agents/skills/devcontainer-wt/references
    cp "$TEMPLATE_DIR/.agents/skills/devcontainer-wt/SKILL.md" \
       .agents/skills/devcontainer-wt/
    cp "$TEMPLATE_DIR/.agents/skills/devcontainer-wt/references/CUSTOMIZING.md" \
       .agents/skills/devcontainer-wt/references/
    success "AI skill files installed."
    ;;
esac

# --- Done ---

echo
success "devcontainer-wt installed successfully!"
echo
info "${BOLD}Next steps:${NC}"
info "  1. Edit .devcontainer/devcontainer.json  -- add language features & extensions"
info "  2. Edit .devcontainer/Dockerfile          -- add system dependencies"
info "  3. Edit .devcontainer/docker-compose.infra.yml -- add infra (Postgres, Redis, etc.)"
info "  4. Edit .env.app.template                 -- add per-worktree env vars"
info "  5. Edit .devcontainer/hooks/post-start.sh -- add project setup (deps, DB, migrations)"
info "  6. Open in VS Code and 'Reopen in Container'"
echo
info "Customization guide:"
info "  https://github.com/${REPO}/blob/${BRANCH}/.agents/skills/devcontainer-wt/references/CUSTOMIZING.md"
echo
